In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
def f(x): 
    return 1/(1+np.exp(-x))

In [3]:
X = [[0,0,1],[1,0,1],[0,1,1],[1,1,1]]
y = [0,1,1,0]

In [4]:
inputs, hiddens, outputs = 3,4,1
np.random.seed(1)
w = 2*np.random.random((inputs,hiddens))-1
omega = 2*np.random.random((hiddens,outputs))-1

In [7]:
for i in range(4):
    neth=np.dot(X[i],w) 
    h = f(neth)
    neto=np.dot(h,omega)
    o = f(neto)

In [5]:
dh=[0,0,0,0]
eta=1
for n in range(10000):
    E=0 # error_sum
    for i in range(4):
        neth=np.dot(X[i],w) 
        h = f(neth)
        neto=np.dot(h,omega) 
        o = f(neto)
        
        E = E + (o-y[i])**2
        do=(o-y[i])*f(neto)*(1-f(neto))
        for j in range(4):
            dh[j]=do*omega[j]*f(neth[j])*(1-f(neth[j]))
            omega[j]=omega[j]-eta*do*h[j]
            for k in range(3):
                w[k][j]=w[k][j]-eta*dh[j]*X[i][k]
E

array([0.00044546])

In [9]:
for i in range(4):
    neth=np.dot(X[i],w) 
    h = f(neth)
    neto=np.dot(h,omega)
    o = f(neto)
    print(o)

[0.00651827]
[0.9894139]
[0.99071994]
[0.01430354]


In [10]:
w,o

(array([[ 2.35603244,  4.41958143, -6.15235168, -6.33134315],
        [ 0.61286955, -6.82944491, -6.20002118,  2.86018093],
        [-1.11258573, -1.72172626,  2.08016084, -0.71621427]]),
 array([0.01430354]))